---
title: "Title title"
date: 2021-11-02
---

theme: minima
title: Title title
author: User1
email: xyz@main.com
description: 
  Bhairava (Sanskrit: भैरव, lit. frightful) is a Shaivite deity worshiped by Hindus. ... 
  Generally in Hinduism, Bhairava is also called Dandapani ("[he who holds the] Danda in [his] hand"), 
  as he holds a rod or Danda to punish sinners, and Swaswa, meaning "whose vehicle is a dog".


twitter_username: bhairav22
github_username:  BhairavBadage

